### ISSUE TITLE
of project and structure and incomplete Readme

### ISSUE THREAD

**Issue by CloudyChris** [eudaldgr/elements#1]
Mate, I don't frankly know how to compile your thing.
Can you give me some help...
I really wanted to have your app installed, but even after I tried to convince valac to look for resources in the folder, it still did not know how to compile your project... 

you can email me at damianfate@gmail.com

Thanks in advance, and nice work :+1:

**Comment by eudaldgr** [comment]
I'm sorry, but it's under construction.
I compile with this comand:

valac --pkg gtk+-3.0 MainWindow.vala Views/*.vala Widgets/*.vala -o elements

But the "app.css" don't work for me.
The screenshot's are made with the stylesheet .css introduced manualy.
I have no idea how to programming, i'm still learning, it's the first thing i made, and i need some help sincerely.
Now i want to connect the thing of Screenshot1.png to the thing on the ScreenshotA.png, maybe the next week.

**Comment by CloudyChris** [comment]
Hey man, I'll take a look and maybe we can figure it out together :) 
Cause again, I'd like to have your app working. It looks really cute

**Comment by eudaldgr** [comment]
Now you can look how it works, it is not finished yet, but have building instructions with integrated stylesheet.
Thanks for your interes. :)
