### ISSUE TITLE
Crashes on run with missing gsettings

### ISSUE THREAD

**Issue by danirabbit** [eudaldgr/elements#2]
It looks like the latest release of elements crashes on startup with the error:

```
(process:4408): GLib-GIO-ERROR **: 13:29:05.014: Settings schema 'com.github.eudaldgr.elements' is not installed

Trace/breakpoint trap
```

As such I've marked this release as "Needs Fixing" in AppCenter

**Comment by eudaldgr** [comment]
it was an issue with hyphens on gschema file. solved
